'use strict';

/**
 * RevBid — Constante Event Types
 * ─────────────────────────────────────────────────────────────────
 * Toate event type-urile folosite în logging, grupate pe domeniu.
 * Folosiți întotdeauna aceste constante — nu strings hardcodate.
 */

const EVENTS = {

  /* ── Autentificare & Cont ── */
  AUTH: {
    REGISTER_SUCCESS:      'AUTH_REGISTER_SUCCESS',
    REGISTER_FAILED:       'AUTH_REGISTER_FAILED',
    EMAIL_VERIFY_SUCCESS:  'AUTH_EMAIL_VERIFY_SUCCESS',
    EMAIL_VERIFY_FAILED:   'AUTH_EMAIL_VERIFY_FAILED',
    RESEND_CODE:           'AUTH_RESEND_CODE',
    LOGIN_SUCCESS:         'AUTH_LOGIN_SUCCESS',
    LOGIN_FAILED:          'AUTH_LOGIN_FAILED',
    LOGIN_BANNED:          'AUTH_LOGIN_BANNED',
    GOOGLE_LOGIN:          'AUTH_GOOGLE_LOGIN',
    LOGOUT:                'AUTH_LOGOUT',
    TOKEN_MISSING:         'AUTH_TOKEN_MISSING',
    TOKEN_INVALID:         'AUTH_TOKEN_INVALID',
    TOKEN_EXPIRED:         'AUTH_TOKEN_EXPIRED',
    PASSWORD_CHANGED:      'AUTH_PASSWORD_CHANGED',
    PASSWORD_CHANGE_FAILED:'AUTH_PASSWORD_CHANGE_FAILED',
    FORGOT_PASSWORD_REQUEST:'AUTH_FORGOT_PASSWORD_REQUEST',
    RESET_EMAIL_SENT:      'AUTH_RESET_EMAIL_SENT',
    RESET_PASSWORD_SUCCESS:'AUTH_RESET_PASSWORD_SUCCESS',
    RESET_TOKEN_INVALID:   'AUTH_RESET_TOKEN_INVALID',
    RESET_RATE_LIMITED:    'AUTH_RESET_RATE_LIMITED',
    PROFILE_UPDATED:       'AUTH_PROFILE_UPDATED',
    AVATAR_UPDATED:        'AUTH_AVATAR_UPDATED',
    ACCOUNT_DELETED:       'AUTH_ACCOUNT_DELETED',
  },

  /* ── Date companie / date fiscale ── */
  COMPANY: {
    UPDATED:        'COMPANY_UPDATED',
    UPDATE_FAILED:  'COMPANY_UPDATE_FAILED',
    ACCESS_DENIED:  'COMPANY_ACCESS_DENIED',
  },

  /* ── Licitații ── */
  AUCTION: {
    CREATED:                'AUCTION_CREATED',
    UPDATED:                'AUCTION_UPDATED',
    CANCELLED:              'AUCTION_CANCELLED',
    CLOSED:                 'AUCTION_CLOSED',
    CLOSED_AUTO:            'AUCTION_CLOSED_AUTO',
    DEADLINE_EXTENDED:      'AUCTION_DEADLINE_EXTENDED',
    WINNER_DETERMINED:      'AUCTION_WINNER_DETERMINED',
    UNAUTHORIZED:           'AUCTION_UNAUTHORIZED',
    NOT_FOUND:              'AUCTION_NOT_FOUND',
    FETCH:                  'AUCTION_FETCH',
    DRAFT_CREATED:          'AUCTION_DRAFT_CREATED',
    DRAFT_UPDATED:          'AUCTION_DRAFT_UPDATED',
    DRAFT_PUBLISHED:        'AUCTION_DRAFT_PUBLISHED',
    DRAFT_DELETED:          'AUCTION_DRAFT_DELETED',
    DRAFT_ACCESS_DENIED:    'AUCTION_DRAFT_ACCESS_DENIED',
    PUBLISH_VALIDATION_FAIL:'AUCTION_PUBLISH_VALIDATION_FAIL',
  },

  /* ── Notificări ── */
  NOTIFY: {
    AUCTION_END_FLOW:   'NOTIFY_AUCTION_END_FLOW',
    AUCTION_END_SKIP:   'NOTIFY_AUCTION_END_SKIP',
    IN_APP_CREATED:     'NOTIFY_IN_APP_CREATED',
    EMAIL_SENT:         'NOTIFY_EMAIL_SENT',
    EMAIL_FAILED:       'NOTIFY_EMAIL_FAILED',
    POPUP_EMITTED:      'NOTIFY_POPUP_EMITTED',
  },

  /* ── Centru de notificări (pagina dedicată) ── */
  NOTIFICATION: {
    LIST_VIEWED:    'NOTIFICATION_LIST_VIEWED',
    MARKED_READ:    'NOTIFICATION_MARKED_READ',
    MARKED_UNREAD:  'NOTIFICATION_MARKED_UNREAD',
    MARK_ALL_READ:  'NOTIFICATION_MARK_ALL_READ',
    DELETED:        'NOTIFICATION_DELETED',
    CLEARED_ALL:    'NOTIFICATION_CLEARED_ALL',
    ACCESS_DENIED:  'NOTIFICATION_ACCESS_DENIED',
  },

  /* ── Invoice / Rezumat tranzacție ── */
  INVOICE: {
    GENERATED:          'INVOICE_GENERATED',
    GENERATE_FAILED:    'INVOICE_GENERATE_FAILED',
    DOWNLOADED:         'INVOICE_DOWNLOADED',
    EMAILED:            'INVOICE_EMAILED',
    ACCESS_DENIED:      'INVOICE_ACCESS_DENIED',
    REGENERATED:        'INVOICE_REGENERATED',
    ADMIN_LIST:         'INVOICE_ADMIN_LIST',
  },

  /* ── Workflow post-licitație (confirmări livrare/primire) ── */
  COMPLETION: {
    DELIVERY_CONFIRMED: 'COMPLETION_DELIVERY_CONFIRMED',
    RECEIPT_CONFIRMED:  'COMPLETION_RECEIPT_CONFIRMED',
    READY_FOR_REVIEW:   'COMPLETION_READY_FOR_REVIEW',
    ACCESS_DENIED:      'COMPLETION_ACCESS_DENIED',
  },

  /* ── Review-uri ── */
  REVIEW: {
    CREATED:           'REVIEW_CREATED',
    DUPLICATE_BLOCKED: 'REVIEW_DUPLICATE_BLOCKED',
    INVALID:           'REVIEW_INVALID',
    ACCESS_DENIED:     'REVIEW_ACCESS_DENIED',
  },

  /* ── Oferte ── */
  BID: {
    CREATED:            'BID_CREATED',
    REJECTED:           'BID_REJECTED',
    UNAUTHORIZED:       'BID_UNAUTHORIZED',
    INVALID_AMOUNT:     'BID_INVALID_AMOUNT',
    WINNING:            'BID_WINNING',
  },

  /* ── Upload ── */
  UPLOAD: {
    SUCCESS:            'UPLOAD_SUCCESS',
    FAILED:             'UPLOAD_FAILED',
    UNAUTHORIZED:       'UPLOAD_UNAUTHORIZED',
    IMAGE_DELETED:      'UPLOAD_IMAGE_DELETED',
    DELETE_FAILED:      'UPLOAD_DELETE_FAILED',
    NO_FILES:           'UPLOAD_NO_FILES',
  },

  /* ── Admin ── */
  ADMIN: {
    USER_BANNED:        'ADMIN_USER_BANNED',
    USER_UNBANNED:      'ADMIN_USER_UNBANNED',
    AUCTION_CLOSED:     'ADMIN_AUCTION_CLOSED',
    LIST_USERS:         'ADMIN_LIST_USERS',
    LIST_AUCTIONS:      'ADMIN_LIST_AUCTIONS',
    ACCESS_DENIED:      'ADMIN_ACCESS_DENIED',
  },

  /* ── Socket / Real-time ── */
  SOCKET: {
    CONNECTED:          'SOCKET_CONNECTED',
    DISCONNECTED:       'SOCKET_DISCONNECTED',
    JOIN_AUCTION:       'SOCKET_JOIN_AUCTION',
    LEAVE_AUCTION:      'SOCKET_LEAVE_AUCTION',
    AUTH_FAILED:        'SOCKET_AUTH_FAILED',
    BID_PLACED:         'SOCKET_BID_PLACED',
    BID_REJECTED:       'SOCKET_BID_REJECTED',
  },

  /* ── Sistem ── */
  SYSTEM: {
    SERVER_START:       'SYSTEM_SERVER_START',
    DB_CONNECTED:       'SYSTEM_DB_CONNECTED',
    DB_ERROR:           'SYSTEM_DB_ERROR',
    JOB_STARTED:        'SYSTEM_JOB_STARTED',
    UNHANDLED_ERROR:    'SYSTEM_UNHANDLED_ERROR',
    VALIDATION_ERROR:   'SYSTEM_VALIDATION_ERROR',
    NOT_FOUND:          'SYSTEM_NOT_FOUND',
  },

  /* ── HTTP ── */
  HTTP: {
    REQUEST:            'HTTP_REQUEST',
    RESPONSE:           'HTTP_RESPONSE',
    ERROR_4XX:          'HTTP_ERROR_4XX',
    ERROR_5XX:          'HTTP_ERROR_5XX',
  },

  /* ── Approval Flow ── */
  APPROVAL: {
    REQUEST_EDIT_CREATED:   'APPROVAL_REQUEST_EDIT_CREATED',
    REQUEST_DELETE_CREATED: 'APPROVAL_REQUEST_DELETE_CREATED',
    REQUEST_APPROVED:       'APPROVAL_REQUEST_APPROVED',
    REQUEST_REJECTED:       'APPROVAL_REQUEST_REJECTED',
    REQUEST_CANCELLED:      'APPROVAL_REQUEST_CANCELLED',
  },

};

module.exports = EVENTS;
